=== jboscomendoza/marvel-snap-cards/marvel-snap-cards.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://github.com/jboscomendoza/marvel-snap-cards/marvel-snap-cards.schema.json",
    "type": "array",
    "default": [],
    "title": "Marvel Snap Cards",
    "items": {
        "type": "object",
        "title": "Card data",
        "required": [
            "name",
            "ability",
            "url",
            "energy",
            "power",
            "series"
        ],
        "properties": {
            "name": {
                "type": "string",
                "title": "Name",
                "description": "Card name, as it appears in game",
                "examples": [
                    "Abomination",
                    "Absorbing Man",
                    "Adam Warlock",
                    "Aero"
                ]
            },
            "ability": {
                "type": "string",
                "title": "Abilities",
                "description": "Card abilities, if a card has no abilities, its flavor text",
                "examples": [
                    "Foolish rabble! You are beneath me!",
                    "On Reveal: If the last card you played has an On Reveal, copy its text. (if it's in play)",
                    "After each turn, draw a card if you're winning here.",
                    "On Reveal: Move the last enemy card played anywhere to this location."
                ]
            },
            "url": {
                "type": "string",
                "title": "URL",
                "description": "Card url in snap.fan.",
                "examples": [
                    "https://snap.fan/cards/Abomination/",
                    "https://snap.fan/cards/AbsorbingMan/",
                    "https://snap.fan/cards/AdamWarlock/",
                    "https://snap.fan/cards/Aero/"
                ]
            },
            "energy": {
                "type": "integer",
                "title": "Energy",
                "description": "Card base energy cost",
                "examples": [
                    5,
                    4
                ]
            },
            "power": {
                "type": "integer",
                "title": "Power",
                "description": "Card base power",
                "examples": [
                    9,
                    4,
                    5
                ]
            },
            "series": {
                "type": "string",
                "title": "Series",
                "description": "Card series, includes Starter and Recruit series",
                "examples": [
                    "Starter",
                    "3"
                ]
            },
            "released": {
                "type": "boolean",
                "title": "Released",
                "description": "Release status for the card, false if scheduled or datamined",
                "examples": [
                    true,
                    false
                ]
            }
        },
        "examples": [{
            "name": "Abomination",
            "ability": "Foolish rabble! You are beneath me!",
            "url": "https://snap.fan/cards/Abomination/",
            "energy": 5,
            "power": 9,
            "series": "Starter",
            "released": true
        },
        {
            "name": "Absorbing Man",
            "ability": "On Reveal: If the last card you played has an On Reveal, copy its text. (if it's in play)",
            "url": "https://snap.fan/cards/AbsorbingMan/",
            "energy": 4,
            "power": 4,
            "series": "3",
            "released": true
        },
        {
            "name": "Adam Warlock",
            "ability": "After each turn, draw a card if you're winning here.",
            "url": "https://snap.fan/cards/AdamWarlock/",
            "energy": 5,
            "power": 5,
            "series": "3",
            "released": true
        },
        {
            "name": "Aero",
            "ability": "On Reveal: Move the last enemy card played anywhere to this location.",
            "url": "https://snap.fan/cards/Aero/",
            "energy": 5,
            "power": 9,
            "series": "3",
            "released": true
        }]
    },
    "examples": [
        [{
            "name": "Abomination",
            "ability": "Foolish rabble! You are beneath me!",
            "url": "https://snap.fan/cards/Abomination/",
            "energy": 5,
            "power": 9,
            "series": "Starter",
            "released": true
        },
        {
            "name": "Absorbing Man",
            "ability": "On Reveal: If the last card you played has an On Reveal, copy its text. (if it's in play)",
            "url": "https://snap.fan/cards/AbsorbingMan/",
            "energy": 4,
            "power": 4,
            "series": "3",
            "released": true
        },
        {
            "name": "Adam Warlock",
            "ability": "After each turn, draw a card if you're winning here.",
            "url": "https://snap.fan/cards/AdamWarlock/",
            "energy": 5,
            "power": 5,
            "series": "3",
            "released": true
        },
        {
            "name": "Aero",
            "ability": "On Reveal: Move the last enemy card played anywhere to this location.",
            "url": "https://snap.fan/cards/Aero/",
            "energy": 5,
            "power": 9,
            "series": "3",
            "released": true
        }]
    ]
}

=== jboscomendoza/marvel-snap-cards/marvel-snap-cards.json
[
  {
    "name":"Abomination",
    "ability":"Foolish rabble! You are beneath me!",
    "url":"https:\/\/snap.fan\/cards\/Abomination\/",
    "energy":5,
    "power":9,
    "series":"Starter",
    "released":true
  },
  {
    "name":"Absorbing Man",
    "ability":"On Reveal: If the last card you played has an On Reveal, copy its text. (if it's in play)",
    "url":"https:\/\/snap.fan\/cards\/AbsorbingMan\/",
    "energy":4,
    "power":4,
    "series":"3",
    "released":true
  },
  {
    "name":"Adam Warlock",
    "ability":"After each turn, draw a card if you're winning here.",
    "url":"https:\/\/snap.fan\/cards\/AdamWarlock\/",
    "energy":5,
    "power":5,
    "series":"3",
    "released":true
  },
  {
    "name":"Aero",
    "ability":"On Reveal: Move the last enemy card played anywhere to this location.",
    "url":"https:\/\/snap.fan\/cards\/Aero\/",
    "energy":5,
    "power":10,
    "series":"3",
    "released":true
  },
  {
    "name":"Agatha Harkness",
    "ability":"Agatha starts in your hand. She plays your cards for you on even turns.",
    "url":"https:\/\/snap.fan\/cards\/AgathaHarkness\/",
    "energy":6,
    "power":14,
    "series":"3",
    "released":true
  },
  {
    "name":"Agent 13",
    "ability":"On Reveal: Add a random card to your hand.",
    "url":"https:\/\/snap.fan\/cards\/Agent13\/",
    "energy":1,
    "power":2,
    "series":"2",
    "released":true
  },
  {
    "name":"Agent Coulson",
    "ability":"On Reveal: Add a random 4-Cost and 5-Cost card to your hand.",
    "url":"https:\/\/snap.fan\/cards\/AgentCoulson\/",
    "energy":3,
    "power":4,
    "series":"3",
    "released":true
  },
  {
    "name":"Agent Venom",
    "ability":"On Reveal: Set the Power of all cards in your deck to 4.",
    "url":"https:\/\/snap.fan\/cards\/AgentVenom\/",
    "energy":2,
    "power":4,
    "series":"5",
    "released":true
  },
  {
    "name":"Agony",
    "ability":"After you play a card here, merge this with it.",
    "url":"https:\/\/snap.fan\/cards\/Agony\/",
    "energy":1,
    "power":2,
    "series":"4",
    "released":true
  },
  {
    "name":"Ajax",
    "ability":"Ongoing: +1 Power for each card in play afflicted with negative Power.",
    "url":"https:\/\/snap.fan\/cards\/Ajax\/",
    "energy":5,
    "power":7,
    "series":"5",
    "released":true
  },
  {
    "name":"Alioth",
    "ability":"On Reveal: Remove the text from all unrevealed enemy cards here.",
    "url":"https:\/\/snap.fan\/cards\/Alioth\/",
    "energy":6,
    "power":10,
    "series":"5",
    "released":true
  },
  {
    "name":"America Chavez",
    "ability":"On Reveal: Give the top card of your deck +2 Power.",
    "url":"https:\/\/snap.fan\/cards\/AmericaChavez\/",
    "energy":1,
    "power":2,
    "series":"1",
    "released":true
  },
  {
    "name":"Angel",
    "ability":"When one of your cards is destroyed, this flies out of your hand or deck to replace it.",
    "url":"https:\/\/snap.fan\/cards\/Angel\/",
    "energy":1,
    "power":2,
    "series":"1",
    "released":true
  },
  {
    "name":"Angela",
    "ability":"After you play a card here,+1 Power.",
    "url":"https:\/\/snap.fan\/cards\/Angela\/",
    "energy":2,
    "power":3,
    "series":"1",
    "released":true
  },
  {
    "name":"Annihilus",
    "ability":"On Reveal: Your cards with Power below 0 switch sides. Destroythose that can't.",
    "url":"https:\/\/snap.fan\/cards\/Annihilus\/",
    "energy":5,
    "power":6,
    "series":"5",
    "released":true
  },
  {
    "name":"Ant Man",
    "ability":"Ongoing: If your side of this location is full, +4 Power.",
    "url":"https:\/\/snap.fan\/cards\/AntMan\/",
    "energy":1,
    "power":1,
    "series":"Recruit",
    "released":true
  },
  {
    "name":"Anti Venom",
    "ability":"On Reveal: Set the Cost and Power of your deck's top card to 0.",
    "url":"https:\/\/snap.fan\/cards\/AntiVenom\/",
    "energy":4,
    "power":6,
    "series":"5",
    "released":true
  },
  {
    "name":"Apocalypse",
    "ability":"When you discard this, put it back with +4 Power.",
    "url":"https:\/\/snap.fan\/cards\/Apocalypse\/",
    "energy":6,
    "power":8,
    "series":"1",
    "released":true
  },
  {
    "name":"Ara\u00f1a",
    "ability":"Activate: Give the next card you play +2 Power and move it to the right.",
    "url":"https:\/\/snap.fan\/cards\/Arana\/",
    "energy":1,
    "power":1,
    "series":"5",
    "released":true
  },
  {
    "name":"Ares",
    "ability":"On Reveal: Compare the Power of the top 3 cards of both decks. If your total is higher, +6 Power.",
    "url":"https:\/\/snap.fan\/cards\/Ares\/",
    "energy":4,
    "power":6,
    "series":"5",
    "released":false
  },
  {
    "name":"Arishem",
    "ability":"At the start of the game, +1 Max Energy. Shuffle 12 random cards into your deck.",
    "url":"https:\/\/snap.fan\/cards\/Arishem\/",
    "energy":7,
    "power":7,
    "series":"5",
    "released":true
  },
  {
    "name":"Armor",
    "ability":"Ongoing: Cards here can'tbe destroyed.",
    "url":"https:\/\/snap.fan\/cards\/Armor\/",
    "energy":2,
    "power":3,
    "series":"1",
    "released":true
  },
  {
    "name":"Arnim Zola",
    "ability":"On Reveal: Destroy one of yourother cards here to copy itat the other locations.",
    "url":"https:\/\/snap.fan\/cards\/ArnimZola\/",
    "energy":6,
    "power":0,
    "series":"3",
    "released":true
  },
  {
    "name":"Attuma",
    "ability":"After each turn, destroy one of your cards here with less Power.",
    "url":"https:\/\/snap.fan\/cards\/Attuma\/",
    "energy":4,
    "power":10,
    "series":"3",
    "released":true
  },
  {
    "name":"Baron Mordo",
    "ability":"On Reveal: The top card of your opponent's deck costs 6 until turn 6.",
    "url":"https:\/\/snap.fan\/cards\/BaronMordo\/",
    "energy":2,
    "power":3,
    "series":"3",
    "released":true
  },
  {
    "name":"Baron Zemo",
    "ability":"On Reveal: Recruit the a card that costs the least from your opponent's deck to your side of this location.",
    "url":"https:\/\/snap.fan\/cards\/BaronZemo\/",
    "energy":3,
    "power":5,
    "series":"5",
    "released":true
  },
  {
    "name":"Bast",
    "ability":"On Reveal: Set the Power of all cards in your hand to 3.",
    "url":"https:\/\/snap.fan\/cards\/Bast\/",
    "energy":1,
    "power":1,
    "series":"3",
    "released":true
  },
  {
    "name":"Beast",
    "ability":"On Reveal: Return your other cards here to your hand. They cost 1 less next turn.",
    "url":"https:\/\/snap.fan\/cards\/Beast\/",
    "energy":3,
    "power":5,
    "series":"3",
    "released":true
  },
  {
    "name":"Beta Ray Bill",
    "ability":"On Reveal: Shuffle Stormbreaker into your deck.",
    "url":"https:\/\/snap.fan\/cards\/BetaRayBill\/",
    "energy":5,
    "power":6,
    "series":"5",
    "released":true
  },
  {
    "name":"Bishop",
    "ability":"After you play a card, this gains +1 Power.",
    "url":"https:\/\/snap.fan\/cards\/Bishop\/",
    "energy":3,
    "power":1,
    "series":"1",
    "released":true
  },
  {
    "name":"Black Bolt",
    "ability":"On Reveal: Discard the card that costs the least from your opponent's hand.",
    "url":"https:\/\/snap.fan\/cards\/BlackBolt\/",
    "energy":5,
    "power":7,
    "series":"3",
    "released":true
  },
  {
    "name":"Black Cat",
    "ability":"If this is in your hand after the turn, discard it.",
    "url":"https:\/\/snap.fan\/cards\/BlackCat\/",
    "energy":4,
    "power":10,
    "series":"3",
    "released":true
  },
  {
    "name":"Black Knight",
    "ability":"After you discard a card, add the Ebony Blade to your hand with that card's Power. (once per game)",
    "url":"https:\/\/snap.fan\/cards\/BlackKnight\/",
    "energy":1,
    "power":2,
    "series":"5",
    "released":true
  },
  {
    "name":"Black Panther",
    "ability":"On Reveal: Double thiscard's Power.",
    "url":"https:\/\/snap.fan\/cards\/BlackPanther\/",
    "energy":5,
    "power":5,
    "series":"3",
    "released":true
  },
  {
    "name":"Black Swan",
    "ability":"Activate: Until the end of next turn, your 1-Cost cards cost 0.",
    "url":"https:\/\/snap.fan\/cards\/BlackSwan\/",
    "energy":2,
    "power":3,
    "series":"5",
    "released":true
  },
  {
    "name":"Black Widow",
    "ability":"On Reveal: Add a Widow's Bite to your opponent's hand.",
    "url":"https:\/\/snap.fan\/cards\/BlackWidow\/",
    "energy":3,
    "power":3,
    "series":"3",
    "released":true
  },
  {
    "name":"Blade",
    "ability":"On Reveal: Discard the rightmost card from your hand.",
    "url":"https:\/\/snap.fan\/cards\/Blade\/",
    "energy":1,
    "power":3,
    "series":"1",
    "released":true
  },
  {
    "name":"Blink",
    "ability":"On Reveal: Swap the last card you played with a card that costs more from your deck.",
    "url":"https:\/\/snap.fan\/cards\/Blink\/",
    "energy":5,
    "power":7,
    "series":"5",
    "released":true
  },
  {
    "name":"Blob",
    "ability":"On Reveal: Merge cards from your deck into this until it gains 13 or more Power.",
    "url":"https:\/\/snap.fan\/cards\/Blob\/",
    "energy":6,
    "power":0,
    "series":"5",
    "released":true
  },
  {
    "name":"Blue Marvel",
    "ability":"Ongoing: Your other cards have +1 Power.",
    "url":"https:\/\/snap.fan\/cards\/BlueMarvel\/",
    "energy":5,
    "power":3,
    "series":"Recruit",
    "released":true
  },
  {
    "name":"Brood",
    "ability":"On Reveal: Add 2 Broodlings here with the same Power.",
    "url":"https:\/\/snap.fan\/cards\/Brood\/",
    "energy":3,
    "power":2,
    "series":"3",
    "released":true
  },
  {
    "name":"Bruce Banner",
    "ability":"When you end a turn with unspent Energy, 25% chance to HULK OUT!",
    "url":"https:\/\/snap.fan\/cards\/BruceBanner\/",
    "energy":2,
    "power":1,
    "series":"5",
    "released":false
  },
  {
    "name":"Bucky Barnes",
    "ability":"When this is destroyed, replace it with the Winter Soldier.",
